#pragma once
#include "../global/types.h"

void LondSecControl(short item_number);

enum LONDSEC_STATES
{
	LONDSEC_EMPTY,
	LONDSEC_WAIT,
	LONDSEC_WALK,
	LONDSEC_RUN,
	LONDSEC_AIM1,
	LONDSEC_SHOOT1,
	LONDSEC_AIM2,
	LONDSEC_SHOOT2,
	LONDSEC_SHOOT3A,
	LONDSEC_SHOOT3B,
	LONDSEC_SHOOT4A,
	LONDSEC_AIM3,
	LONDSEC_AIM4,
	LONDSEC_DEATH,
	LONDSEC_SHOOT4B,
	LONDSEC_DUCK,
	LONDSEC_DUCKED,
	LONDSEC_DUCKAIM,
	LONDSEC_DUCKSHOT,
	LONDSEC_DUCKWALK,
	LONDSEC_STAND
};
