#pragma once
#include "../global/types.h"

void OilRedControl(short item_number);

enum OILRED_STATES
{
	OILRED_EMPTY,
	OILRED_WAIT,
	OILRED_WALK,
	OILRED_RUN,
	OILRED_AIM1,
	OILRED_SHOOT1,
	OILRED_AIM2,
	OILRED_SHOOT2,
	OILRED_SHOOT3A,
	OILRED_SHOOT3B,
	OILRED_SHOOT4A,
	OILRED_AIM3,
	OILRED_AIM4,
	OILRED_DEATH,
	OILRED_SHOOT4B,
	OILRED_DUCK,
	OILRED_DUCKED,
	OILRED_DUCKAIM,
	OILRED_DUCKSHOT,
	OILRED_DUCKWALK,
	OILRED_STAND
};
