#pragma once
#include "../global/types.h"

void TribeAxeControl(short item_number);

enum TRIBEAXE_STATES
{
	TRIBEAXE_EMPTY,
	TRIBEAXE_WAIT1,
	TRIBEAXE_WALK,
	TRIBEAXE_RUN,
	TRIBEAXE_ATTACK1,
	TRIBEAXE_ATTACK2,
	TRIBEAXE_ATTACK3,
	TRIBEAXE_ATTACK4,
	TRIBEAXE_AIM3,
	TRIBEAXE_DEATH,
	TRIBEAXE_ATTACK5,
	TRIBEAXE_WAIT2,
	TRIBEAXE_ATTACK6
};
